language: go
sudo: required
addons:
  apt:
    packages:
    - lynx
    - jq
    - curl
go:
- '1.10'
before_script:
- sudo rsync -az ${TRAVIS_BUILD_DIR}/ /usr/local/bootstrap/
- pushd packer
- if [ $VAGRANT_CLOUD_TOKEN ] ; then packer validate template.json ; fi
- popd
script:
- source ./var.env
- export LEADER_IP=127.0.0.1
- bash scripts/install_factory_service.sh
- sudo cp /usr/local/bin/VaultServiceIDFactory /home/travis/VaultServiceIDFactory
deploy:
  provider: releases
  api_key:
    secure: aM7Sm+exiSFbnx/RenmcM1XhpUTYbmsWohAIhHqVJpMsyeAlvKrG4zJyQJdd03QV1oQ0FzYARsztIQGlBOvS9/AyTQxGmefraf++/MH3ew/cWp9VnKst7ZoSRFvo6SafYsl0RNdVrQIBQl6FaM+jFMQ/kNcBpHik/0UJxkYCP8TBAb5mHafyp5Ojc7bFBP2z8TOX0g5t7Lll/xECh1EDnKSilF1qGjuwGiApnF4D3a7SCMfA5yU2HQGltSvcTdoMKHBMly6MeiTBVbSIy1ElBNOltKRcAGaVD6rj5GNlxFXAyhzQYlLH4kUnvodU/zo0K5Wg/L6DcEsKpj7znRmxH0glIpRp0CLOQD1GqDP1DzXgW0bF9rrlJ9G1uIsHOkshsXPgcwqXEVQIzfWNrbbOzAvVw5d+ifSGujLD+3A262L1vv4lQDykviLsK30ZmylTK1WD2uTgq/rkYFdX2U903h43PADW9iWgp/Te/DzrDKbAg47hFwD62vYUy/zgfRWov9uiGH517VfJrnCS5pd/Tz1J3Vckw2FWUFlGhgLQLys8pQsdiQqqxSfxhXdnSdUKWhCtK/3ZI+Bb1tCAou4hsFCqPE8HM7a3D2FySbILoTwOi1UpQ7tx5u1jj9Hi/EA+C/cKY69igreCU2NCUt9grzeF6IfGF0bOZhsRsJtHq4U=
  file: "/usr/local/bin/VaultServiceIDFactory"
  on:
    repo: allthingsclowd/VaultServiceIDFactory
    tags: true
    
