language: go
sudo: required
addons:
  apt:
    packages:
    - lynx
    - jq
    - curl
go:
- '1.10'

before_script:
- sudo rsync -az ${TRAVIS_BUILD_DIR}/ /usr/local/bootstrap/
- pushd packer
- if [ $VAGRANT_CLOUD_TOKEN ] ; then packer validate template.json ; fi
- popd
script:
- source ./var.env
- export LEADER_IP=127.0.0.1
- bash scripts/install_factory_service.sh
- sudo cp /usr/local/bin/VaultServiceIDFactory /home/travis/VaultServiceIDFactory
deploy:
  provider: releases
  api_key:
    secure: "ZZRYxzcMj2XDUO/YuV6JDnN8OoSSAfhS3edXuXTsZQsSfd7szIWDiIsmOo8YCwNiLMMxmpTkEQ4qLc6as8nVT4kA4THuEEpLIWjxM1yqFKWdAhAol8WI+WXuL7nka2Y6krHyn1IEK9nUJOzYGBIm5cW/2vKx47Pge8Fr9S3uiVyZBRhd9vazOrwwdfEca3i9eKtyXeMXtgot99pk9kVbF/SCur3OBiNIDqvY5e0YRaec/5z8of4Vfrc4v0sJrN7p91NvALUiqUOJen0BtRxQQrUZxE2WJ/WV7iVgJ0gYUAZ00NxMAiZth4Tb6P1apyYI+atiVHsWPmBMiGjiklRoOok9z/3XJU2ZmXtDGfRW7dk6zt+7dvgwOkUV+5DIEx7NCGQlrGny+8M9MoZUSUy+oIT+0UmunmXAaOgEicHQy+KtRYgT2OsguPRXjs0pWiQn1IEtiOgILNQkggvYnN0eOvs+ZbSyG1hyXISePosfUJkySMqu75mQq7ZlefFAiDev3NcJmFRi2ZBkqRRJe2LXVYTyu2inVXjg/kTwunG7gPy2pHH0Cveu9alD6sQ9S6pL3Jfh0GpcSv3Fn54XTclPfnWrH+6S6zNINKlt33NSer8BDld0rmgwoyTwFn7TC74m93C9p9N27RCVvHu6LzGp7X7R+yZKNqVgy7RmMS/C2DI="  file_glob: true
  file: 
    - "/usr/local/bin/VaultServiceIDFactory"
  skip_cleanup: true
  on:
    repo: allthingsclowd/VaultServiceIDFactory
    tags: true
