---
apiVersion: v1
kind: Service
metadata:
  name: vaultsecretidfactory
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  vaultsecretidfactory_mapping
      prefix: /vaultsecretidfactory/
      service: vaultsecretidfactory
spec:
  selector:
    app: vaultsecretidfactory
  ports:
  - port: 8080
    name: vaultsecretidfactory
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vaultsecretidfactory
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vaultsecretidfactory
    spec:
      containers:
      - name: vaultsecretidfactory
        image: allthingscloud/vaultsecretidfactory
        ports:
        - name: http-api
          containerPort: 8080
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi